# Plasmic workflow v4
name: Sync, build and deploy app

permissions:
  contents: read

on:
  push:
    branches: [main]

jobs:
  job:
    name: Sync, build and deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checking out repository...
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: node
        name: Setting up node v20...
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - id: install
        name: Installing dependencies...
        run: |
          cd ${{ github.event.client_payload.data.directory || '.' }}
          npm ci || npm install

      - id: app-build
        name: Building React app...
        run: |
          cd ${{ github.event.client_payload.data.directory || '.' }}
          npm run build

      # - id: prepare-files
      #   name: Preparing files for Walrus deployment...
      #   run: |
      #     # Debug - see what's in the current directory
      #     echo "Current directory: $(pwd)"
      #     echo "Directory contents:"
      #     ls -la

      #     # Create deploy directory with only files
      #     mkdir -p walrus-deploy

      #     # Copy public files if they exist
      #     if [ -d "public" ]; then
      #       echo "Copying files from public directory"
      #       find "public" -type f | while read file; do
      #         newfile="walrus-deploy/$(echo "$file" | sed 's/\//-/g')"
      #         cp "$file" "$newfile"
      #         echo "Copied $file to $newfile"
      #       done
      #     fi

      #     # Debug - list files in walrus-deploy
      #     echo "Files in walrus-deploy:"
      #     find walrus-deploy -type f | sort
      #     echo "Created $(find walrus-deploy -type f | wc -l) files in walrus-deploy"
      - name: Debug directory structure
        run: |
          cd ${{ github.event.client_payload.data.directory || '.' }}
          ls -la
          ls -la dist/

      - id: deploy
        name: Deploy to Walrus Sites
        uses: zktx-io/walrus-sites-provenance@v0.3.4
        with:
          config-path: "./site.config.json"
        env:
          ED25519_PRIVATE_KEY: "${{ secrets.ED25519_PRIVATE_KEY }}"
