name: Sync, build and deploy Plasmic app

permissions:
  contents: write
  pull-requests: write

on:
  repository_dispatch:
    types: [plasmic]
  push:
    branches: [ main ]

jobs:
  job:
    name: Sync, build and deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checking out repository...
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: node
        name: Setting up node v20...
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - id: cache
        name: Recovering cache...
        uses: actions/cache@v4
        with:
          key: lock-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
          path: ${{ github.event.client_payload.data.directory }}/node_modules
      - id: deploy
        name: Deploy to Walrus Sites
        uses: zktx-io/walrus-sites-provenance@v0.3.4
        with:
          config-path: './site.config.json'
        env:
          ED25519_PRIVATE_KEY: "suiprivkey1qrej3l7f6lpcsztuwuvpcygs9sxxc498eazv3fx797tqfyqeklx2wtu7zl3"
